name: Build

on:
  push:
    branches: [ "master", "workflows" ]
  # pull_request:
  #   branches: [ "master", "workflows" ]

jobs:
  upload:
    name: Generate Artifacts
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [windows, linux, darwin]
        arch: [amd64, arm64]
    
    steps:
      - uses: actions/checkout@v4

      - name: Get version tag
        id: get-tag
        run: |
          GIT_TAG=$(git describe)
          RESULT=$?

          if [ $RESULT -eq 0 ]; then
            echo "tag=GIT_TAG" >> $GITHUB_OUTPUT
            echo "Got version tag: $GIT_TAG"
          else
            exit 1
          fi
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.4'
  
      - name: Build
        run: |
          mkdir -p ci-build
          GOOS=${{ matrix.target }} GOARCH=${{ matrix.arch }} go build \
            -v \
            -o ci-build \
            ./...
  
          # TODO (Linux): use static musl for better compat on portablity
          # TODO (macOS): use signing key (using secrets API) and universal binary support
  

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: u64-remote-${{ matrix.target }}-${{ matrix.arch }}-${{ steps.get-tag.outputs.tag }}
          path: ci-build
      
