name: Build

on:
  push:
    branches: [ "master", "workflows" ]
  # pull_request:
  #   branches: [ "master", "workflows" ]

jobs:
  grab-tags:
    name: Grab Git Tags
    runs-on: ubuntu-latest
    
    outputs:
      git-tag: ${{ steps.git-tag.outputs.tag }}
    steps:
      - id: git-tag
        run: echo "tag=$(git describe --tags)" >> "$GITHUB_OUTPUT"
  upload:
    name: Generate Artifacts
    runs-on: ubuntu-latest
    needs: grab-tags

    strategy:
      matrix:
        target: [windows, linux, darwin]
        arch: [amd64, arm64]
    
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.4'
  
      - name: Build
        run: |
          mkdir -p ci-build
          GOOS=${{ matrix.target }} GOARCH=${{ matrix.arch }} go build \
            -v \
            -o ci-build \
            ./...
  
          # TODO (Linux): use static musl for better compat on portablity
          # TODO (macOS): use signing key (using secrets API) and universal binary support
  

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: u64-remote-${{ matrix.target }}-${{ matrix.arch }}-${{ needs.grab-tags.outputs.git-tag }}
          path: ci-build
      
